In [1]:
state = input('New Jersey: ').lower()

In [3]:
# Extract all values
cursor.execute('''SELECT unit_type,no_bdrm,tenure,rel_value, sum(dm_ppl),sum(dm_age04),sum(dm_age5_17),sum(dm_age18_34),sum(dm_age35_44),sum(dm_age45_54),sum(dm_age55_64),sum(dm_age65_74),sum(dm_age75pls)
                    FROM (SELECT st,unit_type,no_bdrm,tenure,rel_value,dm_ppl,dm_age04,dm_age5_17,dm_age18_34,dm_age35_44,dm_age45_54,dm_age55_64,dm_age65_74,dm_age75pls FROM housing_data.`database sel_typ` WHERE st=%s) as new_table
                    GROUP BY unit_type,no_bdrm,tenure,rel_value;''',(New Jersey,))
data1 = cursor.fetchall()
# Extract SFD SFA ...
cursor.execute('''SELECT unit_type,no_bdrm,tenure,rel_value, sum(dm_ppl),sum(dm_age04),sum(dm_age5_17),sum(dm_age18_34),sum(dm_age35_44),sum(dm_age45_54),sum(dm_age55_64),sum(dm_age65_74),sum(dm_age75pls)
                    FROM (SELECT st,unit_type,no_bdrm,tenure,rel_value,dm_ppl,dm_age04,dm_age5_17,dm_age18_34,dm_age35_44,dm_age45_54,dm_age55_64,dm_age65_74,dm_age75pls FROM housing_data.`database valTRC_sel_typ` WHERE st=%s) as new_table
                    GROUP BY unit_type,no_bdrm,tenure,rel_value;''',(New Jersey,))
data2 = cursor.fetchall()

# Extract all values for all housing units
cursor.execute('''SELECT unit_type,no_bdrm,tenure,rel_value, sum(dm_ppl),sum(dm_age04),sum(dm_age5_17),sum(dm_age18_34),sum(dm_age35_44),sum(dm_age45_54),sum(dm_age55_64),sum(dm_age65_74),sum(dm_age75pls)
                    FROM (SELECT st,unit_type,no_bdrm,tenure,rel_value,dm_ppl,dm_age04,dm_age5_17,dm_age18_34,dm_age35_44,dm_age45_54,dm_age55_64,dm_age65_74,dm_age75pls FROM housing_data.`database sel_ALLtyp` WHERE st=%s) as new_table
                    GROUP BY unit_type,no_bdrm,tenure,rel_value;''',(New Jersey,))
data3 = cursor.fetchall()
# Extract SFD SFA for all housing units
cursor.execute('''SELECT unit_type,no_bdrm,tenure,rel_value, sum(dm_ppl),sum(dm_age04),sum(dm_age5_17),sum(dm_age18_34),sum(dm_age35_44),sum(dm_age45_54),sum(dm_age55_64),sum(dm_age65_74),sum(dm_age75pls)
                    FROM (SELECT st,unit_type,no_bdrm,tenure,rel_value,dm_ppl,dm_age04,dm_age5_17,dm_age18_34,dm_age35_44,dm_age45_54,dm_age55_64,dm_age65_74,dm_age75pls FROM housing_data.`database valTRC_sel_ALLtyp` WHERE st=%s) as new_table
                    GROUP BY unit_type,no_bdrm,tenure,rel_value;''',(New Jersey,))
data4 = cursor.fetchall()

# Join all values with other unit types
data = data1 + data2
grouped_data = {}
for row in data:
    unit_type, no_bdrm, tenure, rel_value, total, age0_4, age5_17, age18_34, age35_44, age45_54, age55_64, age65_74, age75_plus = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data:
        grouped_data[key] = []
    grouped_data[key].append((rel_value, total, age0_4, age5_17, age18_34, age35_44, age45_54, age55_64, age65_74, age75_plus))

# Prepare data for tabulate and CSV
formatted_data = []
csv_data = []
for key, values in grouped_data.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", "", "", "", "", "", "", "", "", ""]
    formatted_data.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}",  "", "", "", "", "", "", "", "", ""]
    csv_data.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, total, age0_4, age5_17, age18_34, age35_44, age45_54, age55_64, age65_74, age75_plus = value
        value_row = [ rel_value, total, age0_4, age5_17, age18_34, age35_44, age45_54, age55_64, age65_74, age75_plus]
        formatted_data.append(value_row)
        csv_value_row = [ rel_value, round(total, 3), round(age0_4, 3), round(age5_17, 3), round(age18_34, 3), round(age35_44, 3), round(age45_54, 3), round(age55_64, 3), round(age65_74, 3), round(age75_plus, 3)]
        csv_data.append(csv_value_row)

# Combine data3 and data4
data_combined_2 = data3 + data4

# Group the combined data (data_combined_2) by unit_type, no_bdrm, and tenure
grouped_data_2 = {}
for row in data_combined_2:
    unit_type, no_bdrm, tenure, rel_value, total, age0_4, age5_17, age18_34, age35_44, age45_54, age55_64, age65_74, age75_plus = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data_2:
        grouped_data_2[key] = []
    grouped_data_2[key].append((rel_value, total, age0_4, age5_17, age18_34, age35_44, age45_54, age55_64, age65_74, age75_plus))

# Prepare data for tabulate and CSV for data_combined_2
formatted_data_2 = []
csv_data_2 = []
for key, values in grouped_data_2.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", "", "", "", "", "", "", "", "", ""]
    formatted_data_2.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}",  "", "", "", "", "", "", "", "", ""]
    csv_data_2.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, total, age0_4, age5_17, age18_34, age35_44, age45_54, age55_64, age65_74, age75_plus = value
        value_row = [ rel_value, total, age0_4, age5_17, age18_34, age35_44, age45_54, age55_64, age65_74, age75_plus]
        formatted_data_2.append(value_row)
        csv_value_row = [ rel_value, round(total, 3), round(age0_4, 3), round(age5_17, 3), round(age18_34, 3), round(age35_44, 3), round(age45_54, 3), round(age55_64, 3), round(age65_74, 3), round(age75_plus, 3)]
        csv_data_2.append(csv_value_row)

# Merge the two sets of data row-wise
merged_formatted_data = formatted_data + formatted_data_2
merged_csv_data = csv_data + csv_data_2

# Print merged data
headers = ["STRUCTURE TYPE/ TENURE", "TOTAL PERSONS", "0-4", "5-17", "18-34", "35-44", "45-54", "55-64", "65-74", "75+"]
df1 = pd.DataFrame(merged_csv_data, columns=headers)
df1

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2141884406.py, line 4)

In [ ]:
# Extract all values
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_sac), sum(dm_sack_5), sum(dm_sac6_8), sum(dm_sac9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12 
                          FROM housing_data.`database sel_typ` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (New Jersey,))
data1 = cursor.fetchall()

# Extract SFD SFA ...
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_sac), sum(dm_sack_5), sum(dm_sac6_8), sum(dm_sac9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12 
                          FROM housing_data.`database valTRC_sel_typ` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (New Jersey,))
data2 = cursor.fetchall()

# Extract all values for all housing units
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_sac), sum(dm_sack_5), sum(dm_sac6_8), sum(dm_sac9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12 
                          FROM housing_data.`database sel_ALLtyp` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (New Jersey,))
data3 = cursor.fetchall()

# Extract SFD SFA for all housing units
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_sac), sum(dm_sack_5), sum(dm_sac6_8), sum(dm_sac9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12 
                          FROM housing_data.`database valTRC_sel_ALLtyp` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (New Jersey,))
data4 = cursor.fetchall()

# Combine and group data
data = data1 + data2
grouped_data = {}
for row in data:
    unit_type, no_bdrm, tenure, rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12 = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data:
        grouped_data[key] = []
    grouped_data[key].append((rel_value, round(dm_sac, 3), round(dm_sack_5, 3), round(dm_sac6_8, 3), round(dm_sac9_12, 3)))

# Prepare data for tabulate and CSV
formatted_data = []
csv_data = []
for key, values in grouped_data.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", "", "", "", ""]
    formatted_data.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}",  "", "", "", ""]
    csv_data.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12 = value
        value_row = [rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12]
        formatted_data.append(value_row)
        csv_value_row = [rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12]
        csv_data.append(csv_value_row)

# Combine data3 and data4
data_combined_2 = data3 + data4

# Group the combined data (data_combined_2) by unit_type, no_bdrm, and tenure
grouped_data_2 = {}
for row in data_combined_2:
    unit_type, no_bdrm, tenure, rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12 = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data_2:
        grouped_data_2[key] = []
    grouped_data_2[key].append((rel_value, round(dm_sac, 3), round(dm_sack_5, 3), round(dm_sac6_8, 3), round(dm_sac9_12, 3)))

# Prepare data for tabulate and CSV for data_combined_2
formatted_data_2 = []
csv_data_2 = []
for key, values in grouped_data_2.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", "", "", "", ""]
    formatted_data_2.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", "", "", "", ""]
    csv_data_2.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12 = value
        value_row = [rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12]
        formatted_data_2.append(value_row)
        csv_value_row = [rel_value, dm_sac, dm_sack_5, dm_sac6_8, dm_sac9_12]
        csv_data_2.append(csv_value_row)

# Merge the two sets of data row-wise
merged_formatted_data = formatted_data + formatted_data_2
merged_csv_data = csv_data + csv_data_2

# Convert the merged data to a DataFrame
headers = ["STRUCTURE TYPE/ TENURE", "TOTAL SAC", "Elementary (K-5)", "High School (6-8)", "High School (9-12)"]
df2 = pd.DataFrame(merged_csv_data, columns=headers)
df2

,STRUCTURE TYPE/ TENURE,TOTAL SAC,Elementary (K-5),High School (6-8),High School (9-12)
0,SFD (2 bdrms) - Own/Rent,,,,
1,all values,0.172,0.086,0.036,0.05
2,first tercile,0.204,0.105,0.04,0.059
3,second tercile,0.18,0.085,0.041,0.054
4,third tercile,0.135,0.07,0.026,0.038
...,...,...,...,...,...
188,All_hsng_types (6+ bdrms) - Rent,,,,
189,all values,0.794,0.324,0.326,0.145
190,first tercile,0.192,0.086,0.086,0.02
191,second tercile,0.25,0.13,0.0,0.12
192,third tercile,1.306,0.516,0.584,0.207

In [ ]:
# Extract all values
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_psc), sum(dm_psck_5), sum(dm_psc6_8), sum(dm_psc9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12 
                          FROM housing_data.`database sel_typ` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (New Jersey,))
data1 = cursor.fetchall()

# Extract SFD SFA ...
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_psc), sum(dm_psck_5), sum(dm_psc6_8), sum(dm_psc9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12 
                          FROM housing_data.`database valTRC_sel_typ` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (New Jersey,))
data2 = cursor.fetchall()

# Extract all values for all housing units
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_psc), sum(dm_psck_5), sum(dm_psc6_8), sum(dm_psc9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12 
                          FROM housing_data.`database sel_ALLtyp` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (New Jersey,))
data3 = cursor.fetchall()

# Extract SFD SFA for all housing units
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_psc), sum(dm_psck_5), sum(dm_psc6_8), sum(dm_psc9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12 
                          FROM housing_data.`database valTRC_sel_ALLtyp` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (New Jersey,))
data4 = cursor.fetchall()

# Combine and group data
data = data1 + data2
grouped_data = {}
for row in data:
    unit_type, no_bdrm, tenure, rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12 = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data:
        grouped_data[key] = []
    grouped_data[key].append((rel_value, round(dm_psc, 3), round(dm_psck_5, 3), round(dm_psc6_8, 3), round(dm_psc9_12, 3)))

# Prepare data for tabulate and CSV
formatted_data = []
csv_data = []
for key, values in grouped_data.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", "", "", "", ""]
    formatted_data.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", "", "", "", ""]
    csv_data.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12 = value
        value_row = [rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12]
        formatted_data.append(value_row)
        csv_value_row = [rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12]
        csv_data.append(csv_value_row)

# Combine data3 and data4
data_combined_2 = data3 + data4

# Group the combined data (data_combined_2) by unit_type, no_bdrm, and tenure
grouped_data_2 = {}
for row in data_combined_2:
    unit_type, no_bdrm, tenure, rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12 = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data_2:
        grouped_data_2[key] = []
    grouped_data_2[key].append((rel_value, round(dm_psc, 3), round(dm_psck_5, 3), round(dm_psc6_8, 3), round(dm_psc9_12, 3)))

# Prepare data for tabulate and CSV for data_combined_2
formatted_data_2 = []
csv_data_2 = []
for key, values in grouped_data_2.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", "", "", "", ""]
    formatted_data_2.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", "", "", "", ""]
    csv_data_2.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12 = value
        value_row = [rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12]
        formatted_data_2.append(value_row)
        csv_value_row = [rel_value, dm_psc, dm_psck_5, dm_psc6_8, dm_psc9_12]
        csv_data_2.append(csv_value_row)

# Merge the two sets of data row-wise
merged_formatted_data = formatted_data + formatted_data_2
merged_csv_data = csv_data + csv_data_2

# Convert the merged data to a DataFrame
headers = ["STRUCTURE TYPE/ TENURE", "TOTAL PSC", "Elementary (K-5)", "High School (6-8)", "High School (9-12)"]
df3 = pd.DataFrame(merged_csv_data, columns=headers)
df3

,STRUCTURE TYPE/ TENURE,TOTAL PSC,Elementary (K-5),High School (6-8),High School (9-12)
0,SFD (2 bdrms) - Own/Rent,,,,
1,all values,0.141,0.07,0.03,0.041
2,first tercile,0.17,0.087,0.033,0.049
3,second tercile,0.153,0.074,0.037,0.043
4,third tercile,0.102,0.049,0.021,0.032
...,...,...,...,...,...
188,All_hsng_types (6+ bdrms) - Rent,,,,
189,all values,0.743,0.324,0.298,0.121
190,first tercile,0.192,0.086,0.086,0.02
191,second tercile,0.25,0.13,0.0,0.12
192,third tercile,1.209,0.516,0.531,0.162

In [ ]:
def execute_query(cursor, state, table_name):
    query = f'''
    SELECT unit_type, no_bdrm, tenure, rel_value, 
           SUM(dm_ppl) AS total_dm_ppl, SUM(units_wght) AS total_units_wght,
           SUM(dm_age04) AS total_age04, SUM(dm_age5_17) AS total_age5_17,
           SUM(dm_age18_34) AS total_age18_34, SUM(dm_age35_44) AS total_age35_44,
           SUM(dm_age45_54) AS total_age45_54, SUM(dm_age55_64) AS total_age55_64,
           SUM(dm_age65_74) AS total_age65_74, SUM(dm_age75pls) AS total_age75pls
    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, 
                 dm_ppl, units_wght, dm_age04, dm_age5_17,
                 dm_age18_34, dm_age35_44, dm_age45_54,
                 dm_age55_64, dm_age65_74, dm_age75pls
          FROM housing_data.`{table_name}` 
          WHERE st=%s) AS new_table
    GROUP BY unit_type, no_bdrm, tenure, rel_value;
    '''
    cursor.execute(query, (state,))
    return cursor.fetchall()

def group_data(data):
    grouped_data = {}
    for row in data:
        unit_type, no_bdrm, tenure, rel_value, dm_ppl, units_wght, *ages = row
        key = (unit_type, no_bdrm, tenure)
        if key not in grouped_data:
            grouped_data[key] = []
        grouped_data[key].append((rel_value, round(dm_ppl, 3), round(units_wght, 3), *ages))
    return grouped_data

def format_grouped_data(grouped_data):
    formatted_data = []
    csv_data = []
    for key, values in grouped_data.items():
        unit_type, no_bdrm, tenure = key
        main_row = [f"{unit_type} ({no_bdrm}) - {tenure}"] + [""] * 9
        formatted_data.append(main_row)
        csv_data.append(main_row)
        
        for value in values:
            rel_value, dm_ppl, units_wght, *ages = value
            value_row = [rel_value, dm_ppl, units_wght] + ages
            formatted_data.append(value_row)
            csv_data.append(value_row)
    return formatted_data, csv_data

# Execute queries and fetch data
data1 = execute_query(cursor, state, 'database sel_typ')
data2 = execute_query(cursor, state, 'database valTRC_sel_typ')
data3 = execute_query(cursor, state, 'database sel_ALLtyp')
data4 = execute_query(cursor, state, 'database valTRC_sel_ALLtyp')

# Combine and group data
combined_data1 = data1 + data2
combined_data2 = data3 + data4

grouped_data1 = group_data(combined_data1)
grouped_data2 = group_data(combined_data2)

# Format the grouped data for output
formatted_data1, csv_data1 = format_grouped_data(grouped_data1)
formatted_data2, csv_data2 = format_grouped_data(grouped_data2)

# Merge the formatted data
merged_formatted_data = formatted_data1 + formatted_data2
merged_csv_data = csv_data1 + csv_data2

# Convert the merged data to a DataFrame
headers = ["STRUCTURE TYPE/ TENURE", "TOTAL PERSONS", "Number of Households", 
           "0-4", "5-17", "18-34", "35-44", "45-54", "55-64", "65-74", "75+"]
df4 = pd.DataFrame(merged_csv_data, columns=headers)

df4.head(5)

,STRUCTURE TYPE/ TENURE,TOTAL PERSONS,Number of Households,0-4,5-17,18-34,35-44,45-54,55-64,65-74,75+
0,SFD (2 bdrms) - Own/Rent,,,,,,,,,,NaN
1,all values,2.022,158228.000,0.089289,0.172447,0.381424,0.200123,0.275438,0.370901,0.305843,0.226287
2,first tercile,2.035,50995.000,0.089911,0.203667,0.360428,0.210236,0.302324,0.405157,0.264751,0.198823
3,second tercile,2.047,54053.000,0.115627,0.179953,0.45485,0.213809,0.292694,0.339204,0.264278,0.186280
4,third tercile,1.983,53180.000,0.061922,0.134882,0.326927,0.176514,0.232117,0.370271,0.387495,0.293287

In [ ]:
def execute_query(cursor, state, table_name):
    query = f'''
    SELECT unit_type, no_bdrm, tenure, rel_value, 
           SUM(dm_ppl) AS total_dm_ppl, SUM(units_wght) AS total_units_wght,
           SUM(dm_age04) AS total_age04, SUM(dm_age5_17) AS total_age5_17,
           SUM(dm_age18_34) AS total_age18_34, SUM(dm_age35_44) AS total_age35_44,
           SUM(dm_age45_54) AS total_age45_54, SUM(dm_age55_64) AS total_age55_64,
           SUM(dm_age65_74) AS total_age65_74, SUM(dm_age75pls) AS total_age75pls
    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, 
                 dm_ppl, units_wght, dm_age04, dm_age5_17,
                 dm_age18_34, dm_age35_44, dm_age45_54,
                 dm_age55_64, dm_age65_74, dm_age75pls
          FROM housing_data.`{table_name}` 
          WHERE st=%s) AS new_table
    GROUP BY unit_type, no_bdrm, tenure, rel_value;
    '''
    cursor.execute(query, (state,))
    return cursor.fetchall()

def group_data(data):
    grouped_data = {}
    for row in data:
        unit_type, no_bdrm, tenure, rel_value, dm_ppl, units_wght, *ages = row
        key = (unit_type, no_bdrm, tenure)
        if key not in grouped_data:
            grouped_data[key] = []
        grouped_data[key].append((rel_value, round(dm_ppl, 3), round(units_wght, 3), *ages))
    return grouped_data

def format_grouped_data(grouped_data):
    formatted_data = []
    csv_data = []
    for key, values in grouped_data.items():
        unit_type, no_bdrm, tenure = key
        main_row = [f"{unit_type} ({no_bdrm}) - {tenure}"] + [""] * 9
        formatted_data.append(main_row)
        csv_data.append(main_row)
        
        for value in values:
            rel_value, dm_ppl, units_wght, *ages = value
            value_row = [rel_value, dm_ppl, units_wght] + ages
            formatted_data.append(value_row)
            csv_data.append(value_row)
    return formatted_data, csv_data

# Execute queries and fetch data
data1 = execute_query(cursor, state, 'database sel_typ')
data2 = execute_query(cursor, state, 'database valTRC_sel_typ')
data3 = execute_query(cursor, state, 'database sel_ALLtyp')
data4 = execute_query(cursor, state, 'database valTRC_sel_ALLtyp')

# Combine and group data
combined_data1 = data1 + data2
combined_data2 = data3 + data4

grouped_data1 = group_data(combined_data1)
grouped_data2 = group_data(combined_data2)

# Format the grouped data for output
formatted_data1, csv_data1 = format_grouped_data(grouped_data1)
formatted_data2, csv_data2 = format_grouped_data(grouped_data2)

# Merge the formatted data
merged_formatted_data = formatted_data1 + formatted_data2
merged_csv_data = csv_data1 + csv_data2

# Convert the merged data to a DataFrame
headers = ["STRUCTURE TYPE/ TENURE", "TOTAL PERSONS", "Number of Households", 
           "0-4", "5-17", "18-34", "35-44", "45-54", "55-64", "65-74", "75+"]
df4 = pd.DataFrame(merged_csv_data, columns=headers)

df4.head(5)

,STRUCTURE TYPE/ TENURE,TOTAL PERSONS,Number of Households,0-4,5-17,18-34,35-44,45-54,55-64,65-74,75+
0,SFD (2 bdrms) - Own/Rent,,,,,,,,,,NaN
1,all values,2.022,158228.000,0.089289,0.172447,0.381424,0.200123,0.275438,0.370901,0.305843,0.226287
2,first tercile,2.035,50995.000,0.089911,0.203667,0.360428,0.210236,0.302324,0.405157,0.264751,0.198823
3,second tercile,2.047,54053.000,0.115627,0.179953,0.45485,0.213809,0.292694,0.339204,0.264278,0.186280
4,third tercile,1.983,53180.000,0.061922,0.134882,0.326927,0.176514,0.232117,0.370271,0.387495,0.293287

In [ ]:
import pandas as pd
import numpy as np

# Define a function to calculate confidence intervals and error margins
def calculate_confidence_interval(row, column_names,mean):
    z_score = 1.645  # Z-score for 90% confidence
    
    # Lists to collect values for each age group
    means = []
    standard_errors = []
    lower_bounds = []
    upper_bounds = []
    error_margins = []
    
    # For each age group, calculate the mean, SE, CI, and Error Margin
    for age_group in column_names:
        
        try:
            # Ensure mean_value is a float
            mean_value = float(row[age_group])
        except (ValueError, TypeError):
            # If conversion fails, skip this row
            continue
        
        total_persons = float(row[mean]) if row[mean] != '' else 0
        if total_persons == 0:
            se = np.nan
        else:
            se = mean_value / np.sqrt(total_persons)
        
        # Calculate confidence intervals
        lower_bound = mean_value - z_score * se
        upper_bound = mean_value + z_score * se
        
        # Calculate error margin as percentage
        error_margin_pct = ((upper_bound - lower_bound) / (2 * mean_value)) *100  if mean_value != 0 else np.nan
        
        # Append values to the lists
        means.append(mean_value)
        standard_errors.append(se)
        lower_bounds.append(lower_bound)
        upper_bounds.append(upper_bound)
        error_margins.append(error_margin_pct)
    
    # Calculate the average values across all age groups
    if len(means) > 0:
        overall_mean = np.nanmean(means)
        overall_se = np.nanmean(standard_errors)
        overall_lower = np.nanmean(lower_bounds)
        overall_upper = np.nanmean(upper_bounds)
        overall_error_margin_pct = np.nanmean(error_margins)
    else:
        # Handle the case where there are no valid values
        overall_mean = overall_se = overall_lower = overall_upper = overall_error_margin_pct = np.nan
    
    # Return the combined results as a single row
    average = float(row[mean]) if row[mean] != '' else 0
     
    if average == 0:
        return pd.Series({
            'Standard Errors': '',
            'Low': '',
            'High': '',
            'Error Margin as %': ''
        })
    else:
        return pd.Series({
            'Standard Errors': overall_se,
            'Low': overall_lower + average,
            'High': overall_upper + average,
            'Error Margin as %': ((overall_upper + average) - (overall_lower + average)) / (2 * average) * 100
        })

# Define your age groups list
age_groups_list = ['0-4', '5-17', '18-34', '35-44', '45-54', '55-64', '65-74', '75+']

# Apply the function to each row
confidence_intervals_df = df4.apply(calculate_confidence_interval, axis=1, column_names=age_groups_list,mean='TOTAL PERSONS')

# Combine the new columns with the original DataFrame
df4 = pd.concat([df4, confidence_intervals_df], axis=1)

# Fill any missing values if needed
df4 = df4.fillna('')
df4 = df4.drop(columns=age_groups_list)  # Drop the original age group columns
# Display the updated DataFrame
df4.head(10)

C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:47: RuntimeWarning: Mean of empty slice
  overall_mean = np.nanmean(means)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:48: RuntimeWarning: Mean of empty slice
  overall_se = np.nanmean(standard_errors)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:49: RuntimeWarning: Mean of empty slice
  overall_lower = np.nanmean(lower_bounds)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:50: RuntimeWarning: Mean of empty slice
  overall_upper = np.nanmean(upper_bounds)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:51: RuntimeWarning: Mean of empty slice
  overall_error_margin_pct = np.nanmean(error_margins)

,STRUCTURE TYPE/ TENURE,TOTAL PERSONS,Number of Households,Standard Errors,Low,High,Error Margin as %
0,SFD (2 bdrms) - Own/Rent,,,,,,
1,all values,2.022,158228.000,0.177725,1.982362,2.567076,14.458804
2,first tercile,2.035,50995.000,0.178343,1.996038,2.582786,14.416413
3,second tercile,2.047,54053.000,0.178815,2.008686,2.596988,14.369851
4,third tercile,1.983,53180.000,0.176061,1.941307,2.520547,14.605129
5,SFD (3 bdrms) - Own/Rent,,,,,,
6,all values,2.577,744999.000,0.200689,2.569033,3.229302,12.810794
7,first tercile,2.602,239226.000,0.201648,2.595562,3.258984,12.748319
8,second tercile,2.672,250424.000,0.204296,2.669881,3.342013,12.577325
9,third tercile,2.462,255349.000,0.196107,2.447111,3.092302,13.102985

In [ ]:
# Extract all values
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_sac), sum(units_wght), sum(dm_sack_5), sum(dm_sac6_8), sum(dm_sac9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12  
                          FROM housing_data.`database sel_typ` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (state,))
data1 = cursor.fetchall()

# Extract SFD SFA ...
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_sac), sum(units_wght), sum(dm_sack_5), sum(dm_sac6_8), sum(dm_sac9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12  
                          FROM housing_data.`database valTRC_sel_typ` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (state,))
data2 = cursor.fetchall()

# Extract all values for all housing units
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_sac), sum(units_wght), sum(dm_sack_5), sum(dm_sac6_8), sum(dm_sac9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12  
                          FROM housing_data.`database sel_ALLtyp` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (state,))
data3 = cursor.fetchall()

# Extract SFD SFA for all housing units
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_sac), sum(units_wght), sum(dm_sack_5), sum(dm_sac6_8), sum(dm_sac9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12  
                          FROM housing_data.`database valTRC_sel_ALLtyp` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (state,))
data4 = cursor.fetchall()

# Combine and group data
data = data1 + data2
grouped_data = {}
for row in data:
    unit_type, no_bdrm, tenure, rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12 = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data:
        grouped_data[key] = []
    grouped_data[key].append((rel_value, round(dm_sac, 3), round(units_wght, 3), round(dm_sack_5, 3), round(dm_sac6_8, 3), round(dm_sac9_12, 3)))

# Prepare data for tabulate and CSV
formatted_data = []
csv_data = []
for key, values in grouped_data.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", ""]
    formatted_data.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", ""]
    csv_data.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12 = value
        value_row = [rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12]
        formatted_data.append(value_row)
        csv_value_row = [rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12]
        csv_data.append(csv_value_row)

# Combine data3 and data4 for SAC and units_wght
data_combined_3 = data3 + data4

# Group the combined data (data_combined_3) by unit_type, no_bdrm, and tenure
grouped_data_3 = {}
for row in data_combined_3:
    unit_type, no_bdrm, tenure, rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12 = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data_3:
        grouped_data_3[key] = []
    grouped_data_3[key].append((rel_value, round(dm_sac, 3), round(units_wght, 3), round(dm_sack_5, 3), round(dm_sac6_8, 3), round(dm_sac9_12, 3)))

# Prepare data for tabulate and CSV for data_combined_3
formatted_data_3 = []
csv_data_3 = []
for key, values in grouped_data_3.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", ""]
    formatted_data_3.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", ""]
    csv_data_3.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12 = value
        value_row = [rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12]
        formatted_data_3.append(value_row)
        csv_value_row = [rel_value, dm_sac, units_wght, dm_sack_5, dm_sac6_8, dm_sac9_12]
        csv_data_3.append(csv_value_row)

# Merge the original and the new formatted data
merged_formatted_data_3 = formatted_data + formatted_data_3
merged_csv_data_3 = csv_data + csv_data_3

# Convert the merged data to a DataFrame
headers = ["STRUCTURE TYPE/ TENURE", "TOTAL SAC", "Number of Households", "SAC 5", "SAC 6-8", "SAC 9-12"]
df5 = pd.DataFrame(merged_csv_data_3, columns=headers)
df5 = df5.fillna('')  # Replace NaN with empty string
df5 = df5.replace({None: ''})
df5.head(5)

,STRUCTURE TYPE/ TENURE,TOTAL SAC,Number of Households,SAC 5,SAC 6-8,SAC 9-12
0,SFD (2 bdrms) - Own/Rent,,,,,
1,all values,0.172,158228.000,0.086,0.036,0.05
2,first tercile,0.204,50995.000,0.105,0.04,0.059
3,second tercile,0.18,54053.000,0.085,0.041,0.054
4,third tercile,0.135,53180.000,0.07,0.026,0.038

In [ ]:
# Apply the function to each row
col = ["SAC 5", "SAC 6-8", "SAC 9-12"]
# Apply the function to each row
confidence_intervals_df5 = df5.apply(calculate_confidence_interval, axis=1, column_names=col,mean='TOTAL SAC')

# Combine the new columns with the original DataFrame
df5 = pd.concat([df5, confidence_intervals_df5], axis=1)

# Fill any missing values if needed
df5 = df5.fillna('')
df5 = df5.drop(columns=col)  # Drop the original age group columns
# Display the updated DataFrame
df5.head(10)

C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:48: RuntimeWarning: Mean of empty slice
  overall_se = np.nanmean(standard_errors)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:49: RuntimeWarning: Mean of empty slice
  overall_lower = np.nanmean(lower_bounds)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:50: RuntimeWarning: Mean of empty slice
  overall_upper = np.nanmean(upper_bounds)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:51: RuntimeWarning: Mean of empty slice
  overall_error_margin_pct = np.nanmean(error_margins)

,STRUCTURE TYPE/ TENURE,TOTAL SAC,Number of Households,Standard Errors,Low,High,Error Margin as %
0,SFD (2 bdrms) - Own/Rent,,,,,,
1,all values,0.172,158228.000,0.138243,0.001924,0.456743,132.214907
2,first tercile,0.204,50995.000,0.150555,0.024338,0.519662,121.403041
3,second tercile,0.18,54053.000,0.141421,0.007362,0.472638,129.243406
4,third tercile,0.135,53180.000,0.121567,-0.020311,0.379645,148.131968
5,SFD (3 bdrms) - Own/Rent,,,,,,
6,all values,0.397,744999.000,0.210026,0.18384,0.874827,87.026075
7,first tercile,0.418,239226.000,0.216025,0.202305,0.913028,85.014743
8,second tercile,0.455,250424.000,0.224846,0.236796,0.976538,81.290342
9,third tercile,0.321,255349.000,0.188856,0.117332,0.738668,96.781452

In [ ]:
# Extract all values
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_psc), sum(units_wght), sum(dm_psck_5), sum(dm_psc6_8), sum(dm_psc9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12  
                          FROM housing_data.`database sel_typ` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (state,))
data1 = cursor.fetchall()

# Extract SFD SFA ...
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_psc), sum(units_wght), sum(dm_psck_5), sum(dm_psc6_8), sum(dm_psc9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12  
                          FROM housing_data.`database valTRC_sel_typ` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (state,))
data2 = cursor.fetchall()

# Extract all values for all housing units
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_psc), sum(units_wght), sum(dm_psck_5), sum(dm_psc6_8), sum(dm_psc9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12  
                          FROM housing_data.`database sel_ALLtyp` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (state,))
data3 = cursor.fetchall()

# Extract SFD SFA for all housing units
cursor.execute('''SELECT unit_type, no_bdrm, tenure, rel_value, sum(dm_psc), sum(units_wght), sum(dm_psck_5), sum(dm_psc6_8), sum(dm_psc9_12)
                    FROM (SELECT st, unit_type, no_bdrm, tenure, rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12  
                          FROM housing_data.`database valTRC_sel_ALLtyp` 
                          WHERE st=%s) as new_table
                    GROUP BY unit_type, no_bdrm, tenure, rel_value;''', (state,))
data4 = cursor.fetchall()

# Combine and group data
data = data1 + data2
grouped_data = {}
for row in data:
    unit_type, no_bdrm, tenure, rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12 = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data:
        grouped_data[key] = []
    grouped_data[key].append((rel_value, round(dm_psc, 3), round(units_wght, 3), round(dm_psck_5, 3), round(dm_psc6_8, 3), round(dm_psc9_12, 3)))

# Prepare data for tabulate and CSV
formatted_data = []
csv_data = []
for key, values in grouped_data.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", ""]
    formatted_data.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", ""]
    csv_data.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12 = value
        value_row = [rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12]
        formatted_data.append(value_row)
        csv_value_row = [rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12]
        csv_data.append(csv_value_row)

# Combine data3 and data4 for PSC and units_wght
data_combined_4 = data3 + data4

# Group the combined data (data_combined_4) by unit_type, no_bdrm, and tenure
grouped_data_4 = {}
for row in data_combined_4:
    unit_type, no_bdrm, tenure, rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12 = row
    key = (unit_type, no_bdrm, tenure)
    if key not in grouped_data_4:
        grouped_data_4[key] = []
    grouped_data_4[key].append((rel_value, round(dm_psc, 3), round(units_wght, 3), round(dm_psck_5, 3), round(dm_psc6_8, 3), round(dm_psc9_12, 3)))

# Prepare data for tabulate and CSV for data_combined_4
formatted_data_4 = []
csv_data_4 = []
for key, values in grouped_data_4.items():
    unit_type, no_bdrm, tenure = key
    # Add main row
    main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", ""]
    formatted_data_4.append(main_row)
    csv_main_row = [f"{unit_type} ({no_bdrm}) - {tenure}", ""]
    csv_data_4.append(csv_main_row)
    
    # Add rel_value rows
    for value in values:
        rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12 = value
        value_row = [rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12]
        formatted_data_4.append(value_row)
        csv_value_row = [rel_value, dm_psc, units_wght, dm_psck_5, dm_psc6_8, dm_psc9_12]
        csv_data_4.append(csv_value_row)

# Merge the original and the new formatted data
merged_formatted_data_4 = formatted_data + formatted_data_4
merged_csv_data_4 = csv_data + csv_data_4

# Convert the merged data to a DataFrame
headers = ["STRUCTURE TYPE/ TENURE", "TOTAL PSC", "Number of Households", "PSC 5", "PSC 6-8", "PSC 9-12"]
df6 = pd.DataFrame(merged_csv_data_4, columns=headers)
df6 = df6.fillna('')  # Replace NaN with empty string
df6 = df6.replace({None: ''})
df6.head(5)

,STRUCTURE TYPE/ TENURE,TOTAL PSC,Number of Households,PSC 5,PSC 6-8,PSC 9-12
0,SFD (2 bdrms) - Own/Rent,,,,,
1,all values,0.141,158228.000,0.07,0.03,0.041
2,first tercile,0.17,50995.000,0.087,0.033,0.049
3,second tercile,0.153,54053.000,0.074,0.037,0.043
4,third tercile,0.102,53180.000,0.049,0.021,0.032

In [ ]:
# Apply the function to each row
col = [ "PSC 5", "PSC 6-8", "PSC 9-12"]
# Apply the function to each row
confidence_intervals_df6 = df6.apply(calculate_confidence_interval, axis=1, column_names=col,mean='TOTAL PSC')

# Combine the new columns with the original DataFrame
df6 = pd.concat([df6, confidence_intervals_df6], axis=1)

# Fill any missing values if needed
df6 = df6.fillna('')
df6 = df6.drop(columns=col)  # Drop the original age group columns
# Display the updated DataFrame
df6.head(10)

C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:48: RuntimeWarning: Mean of empty slice
  overall_se = np.nanmean(standard_errors)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:49: RuntimeWarning: Mean of empty slice
  overall_lower = np.nanmean(lower_bounds)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:50: RuntimeWarning: Mean of empty slice
  overall_upper = np.nanmean(upper_bounds)
C:\Users\Digital Traders\AppData\Local\Temp\ipykernel_15788\3397572921.py:51: RuntimeWarning: Mean of empty slice
  overall_error_margin_pct = np.nanmean(error_margins)

,STRUCTURE TYPE/ TENURE,TOTAL PSC,Number of Households,Standard Errors,Low,High,Error Margin as %
0,SFD (2 bdrms) - Own/Rent,,,,,,
1,all values,0.141,158228.000,0.125167,-0.017899,0.393899,146.027648
2,first tercile,0.17,50995.000,0.136628,0.00158,0.451087,132.208071
3,second tercile,0.153,54053.000,0.131236,-0.01155,0.420217,141.100393
4,third tercile,0.102,53180.000,0.106458,-0.039124,0.311124,171.689826
5,SFD (3 bdrms) - Own/Rent,,,,,,
6,all values,0.334,744999.000,0.192642,0.128437,0.76223,94.879287
7,first tercile,0.36,239226.000,0.2,0.151,0.809,91.388889
8,second tercile,0.387,250424.000,0.2079,0.174337,0.858329,88.371032
9,third tercile,0.257,255349.000,0.169641,0.06394,0.62206,108.583708

In [ ]:
######
filename = f'17_{state}_all_housing_units.xlsx'
# Write data to CSV
with pd.ExcelWriter(filename, engine='openpyxl') as writer:
    df1.to_excel(writer, sheet_name='TABLE IIB1', index=False)
    df2.to_excel(writer, sheet_name='TABLE IIB2', index=False)
    df3.to_excel(writer, sheet_name='TABLE IIB3', index=False)
    df4.to_excel(writer, sheet_name='TABLE IIB4', index=False)
    df5.to_excel(writer, sheet_name='TABLE IIB5', index=False)
    df6.to_excel(writer, sheet_name='TABLE IIB6', index=False)




# Close the database connection
cursor.close()
conn.close()